<div class="message-container d-flex justify-content-end mb-4 <?php echo $type?>">
    <div class="message rounded w-100 p-3">
        <p class="mb-0"><?php echo $text;?></p>
    </div>
    <div class="user-image rounded-circle" onclick="location.href='profile'">
        <?php if($type == 'received'): ?>
            <small class="online rounded-circle"></small>
        <?php endif;?>
        </div>
</div>
