<section id="profile-image" onclick="location.href='chat'">
    <div class="image rounded-circle"></div>
    <small class="status text-uppercase rounded-circle">Online</small>
</section>
<section class="info mb-auto">
    <div>
        <div class="text">
            <h4 class="title mb-0">Sophie, 22</h4>
            <span class="subtitle align-text-top">New York</span>
        </div>
        <div class="rate">
            <div class="star"></div>
        </div>
    </div>
    <div class="description">
        <p>
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nulla quam velit, vulputate eu pharetra nec, mattis ac neque.
        </p>
    </div>
</section>
<button id="add-friend" class="button dark text-uppercase border-0" onclick="addFriend()"><span>Add as friend</span></button>
